username: Daschi1
password: Fdb6h4iUnU2KBaz
clientId: Hd0tnY6HnmaXOQ
secret: imv_-Ic3r6MWLH-2bg7RzvpScIU
index: 2
ignoreHorizontal: true
images:
  20|27|6|2020:
    '0':
      name: Deep in the Amazonas region of Peru, you'll find the 2,500 foot tall Gocta
        Waterfalls. [1366x2048] [OC]
      imageUrl: https://i.redd.it/izi3ztefrh751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgy4oo/deep_in_the_amazonas_region_of_peru_youll_find/
    '1':
      name: Rainbow emerging from the mist at Victoria Falls in Zambia [1350x1080]
        [OC] IG @mvttmic
      imageUrl: https://i.redd.it/as0gdurish751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgy7di/rainbow_emerging_from_the_mist_at_victoria_falls/
    '2':
      name: Pacifica, CA [OC] [4032x3024]
      imageUrl: https://i.redd.it/0pq2hqacuh751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgye88/pacifica_ca_oc_4032x3024/
    '3':
      name: A storm rolling in - Cannon Beach, Oregon [oc][1616x1080]
      imageUrl: https://i.redd.it/vjdl97snxh751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgypzj/a_storm_rolling_in_cannon_beach_oregon_oc1616x1080/
    '4':
      name: Milky Way over Bighorn Fire in Oracle, Arizona [OC] [6000x4000]
      imageUrl: https://i.redd.it/iyjtmmbjzh751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgywwn/milky_way_over_bighorn_fire_in_oracle_arizona_oc/
    '5':
      name: Epic nature at Wallace falls, WA, US [OC] [4032x3024]
      imageUrl: https://i.redd.it/26nytp920i751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgyz7w/epic_nature_at_wallace_falls_wa_us_oc_4032x3024/
    '6':
      name: "Gateway of trees Frederick, MD. [OC] (4032\xd73024)"
      imageUrl: https://i.redd.it/if62chxrrh751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgy4nh/gateway_of_trees_frederick_md_oc_40323024/
  21|27|6|2020:
    '0':
      name: A storm rolling in - Cannon Beach, Oregon [oc][1616x1080]
      imageUrl: https://i.redd.it/vjdl97snxh751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgypzj/a_storm_rolling_in_cannon_beach_oregon_oc1616x1080/
    '1':
      name: Epic nature at Wallace falls, WA, US [OC] [4032x3024]
      imageUrl: https://i.redd.it/26nytp920i751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgyz7w/epic_nature_at_wallace_falls_wa_us_oc_4032x3024/
    '2':
      name: Monument Valley UT [4160x3120] [OC]
      imageUrl: https://i.redd.it/bnb6rcnh1i751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgz3z5/monument_valley_ut_4160x3120_oc/
    '3':
      name: Hidden beach; Puerto Rico [OC] [4000x3000]
      imageUrl: https://i.redd.it/2tmjgog05i751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgzh1h/hidden_beach_puerto_rico_oc_4000x3000/
    '4':
      name: "Forest in Germany(Fuldatal) [OC] [4032\xd73024]"
      imageUrl: https://i.redd.it/m6k6kd5q4i751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgzg03/forest_in_germanyfuldatal_oc_40323024/
    '5':
      name: "Schrecksee Germany, most difficult hike I have done to this day. In the\
        \ end swimming in 45 degree (f) water was definitely worth it. (5184\xd73456)(OC)"
      imageUrl: https://i.redd.it/uf91clsf5i751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgzitj/schrecksee_germany_most_difficult_hike_i_have/
  22|27|6|2020:
    '0':
      name: Skakavac, Sarajevo, Bosnia and Herzegovina [4032x3024] [OC]
      imageUrl: https://i.redd.it/9t3hw078ai751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgzzux/skakavac_sarajevo_bosnia_and_herzegovina/
    '1':
      name: Last night just after sunset, Eastville Virginia Dunes, Chesapeake Bay.
        [2448x3264] [OC]
      imageUrl: https://i.redd.it/uumull1iai751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hh00xg/last_night_just_after_sunset_eastville_virginia/
    '2':
      name: Camel's Hump, Vermont (OC) [3955x2816]
      imageUrl: https://i.redd.it/pgp9zlpr5i751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgzknd/camels_hump_vermont_oc_3955x2816/
    '3':
      name: Those golden days! Sudbury - Canada [OC] [4016x6016] @jon.inreallife
      imageUrl: https://i.redd.it/ks8zagc97i751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgzr75/those_golden_days_sudbury_canada_oc_4016x6016/
    '4':
      name: Mt. Rainier just after sunset [OC] {2160x1440]
      imageUrl: https://i.redd.it/togit94tbi751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hh06te/mt_rainier_just_after_sunset_oc_2160x1440/
    '5':
      name: Took this picture today while hiking around Kreuzteich Lake in Styria,Austria
        [4608x3456] [OC]
      imageUrl: https://i.redd.it/g461gvz09i751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hgzvi3/took_this_picture_today_while_hiking_around/
    '6':
      name: Sunset in Tenerife, mesas del mar [1920x1080] OC
      imageUrl: https://i.redd.it/ul4bqi77fi751.jpg
      permanentUrl: https://www.reddit.com/r/EarthPorn/comments/hh0hvn/sunset_in_tenerife_mesas_del_mar_1920x1080_oc/
